### ISSUE TITLE
ruby splat args confuse evil-matchit

### ISSUE THREAD

**Issue by Silex** [redguardtoo/evil-matchit#100]
Hello,

``` ruby
define_method(method) do |*args|
end
```

The `*` confuses matchit, probably because https://github.com/redguardtoo/evil-matchit/blob/master/evil-matchit-ruby.el#L37 does not include `*` as the possible characters

**Comment by redguardtoo** [comment]
00ab601 support "define_method(method) do |*args|" (Chen Bin)

**Comment by Silex** [comment]
:+1: Thanks
