### ISSUE TITLE
Jumps don't get added to the jump list

### ISSUE THREAD

**Issue by eli-rodriguezperez** [redguardtoo/evil-matchit#104]
Hi, I'm getting this thing where using `%` with `evil-matchit` doesn't add the jump to the jumplist, so when trying to use `Ctrl-o` it makes it confusing. With `evil-matchit` disabled it works as intended. I've attached a gif where I'm showing the problem, first I try to `%` then `Ctrl-O` then try the same with `evil-matchit` disabled and so with the default behaviour from the `evil` layer.

I don't know if that's the intended usage or if it's a bug, I'm using win7 if that's of any help, with msys64 version of emacs.

![evil-matchit jump list](https://user-images.githubusercontent.com/22303147/57616900-ad483e00-757f-11e9-943f-a3f7d0f9afe2.gif)

**Comment by redguardtoo** [comment]
What's jump list?

**Comment by eli-rodriguezperez** [comment]
So in vim and also in evil, everytime you make use of a command that results in a movement it gets stored in a list called the jump list. You can navigate through that list with `Ctrl-o` to go back through the list and `Ctrl-i` to navigate it forward and so the cursor will jump to that position. It's normally used when jumping through grep result buffers but also really useful when using macros. I checked and it's implemented in [`evil-commands.el`](https://github.com/emacs-evil/evil/blob/master/evil-commands.el).

I can try and help with that feature. As far as I know `evil` is listed as a dependency so there should be no problem.

**Comment by redguardtoo** [comment]
Sure, a pull request is welcomed.

**Comment by eli-rodriguezperez** [comment]
Great, will try to work on it when I can.

**Comment by ianpan870102** [comment]
Friendly p.s.: this issue can be closed. One can use `Ctrl-o` to jump back to previous locations.
