### ISSUE TITLE
Ruby matches `case` within strings

### ISSUE THREAD

**Issue by kriansa** [redguardtoo/evil-matchit#111]
Using `%` to jump around marks that includes a string starting with one of the Ruby keywords will not work properly.

Example:

```ruby
def my_function
  my_string = 
    "SELECT field,
    case when result = 1 then 'Yes' else 'No' end 
    FROM table"

  puts my_string
end
```

Pressing `%` to jump on `end` will match the `case` on the string. `def` will not find a match. This only happens if a the string is multiline and there's a line starting with one of the Ruby jump matchers.

**Comment by redguardtoo** [comment]
5e92e37 better algorithm to match keyword (Chen Bin)

**Comment by kriansa** [comment]
This is fixed. Awesome work! :bowing_man: :tada:
