### ISSUE TITLE
Can't match tags in blade.php files in Laravel framework

### ISSUE THREAD

**Issue by mauchchhash** [redguardtoo/evil-matchit#113]
I cannot match start and end html tags in laravel framework's blade.php files. ie: example.blade.php.
Here's and example for you to try: [Blade Example](https://github.com/mauchchhash/simplePOS/blob/master/resources/views/layouts/app.blade.php)

**Comment by redguardtoo** [comment]
What's your major mode (`C-h v major-mode`)? What tag can't match?

**Comment by mauchchhash** [comment]
My major mode is php when using `.blade.php` files. I am using spacemacs..

**Comment by redguardtoo** [comment]
Sorry. I forget to add `php-mode`. I assume everybody is using `web-mode` these days. php keywords are already there.

2a53963 support php-mode (Chen Bin)

Actually, every piece of evil-matchit is configurable. You can use below code to support `php-mode`,
```
(evilmi-load-plugin-rules '(web-mode
                              html-mode
                              nxml-mode
                              nxhtml-mode
                              sgml-mode
                              php-mode
                              message-mode
                              mhtml-mode)
                            '(template simple html))
```

**Comment by mauchchhash** [comment]
Thanks.I am new in emacs. Can u tell how to update this change in emacs using git pull instead of hunting down the evil-matchit.el file and mannually adding the change? Pardon my ignorance.

**Comment by redguardtoo** [comment]
It take a few hours for melpa to pick up my changes change. I'm not familar with spacemacs.

Usually I just upgrade packages using Emacs' official way. `M-x list-packages`, press `U`, then press `x`.

**Comment by mauchchhash** [comment]
Yes it's working now. Thank you very much.
