### ISSUE TITLE
evilmi-select-items behaviour is a little weird when cursor is inside a {(["<>

### ISSUE THREAD

**Issue by linchen2chris** [redguardtoo/evil-matchit#117]
evilmi-select-items can select the content when cursor is on a {(["<>, but if cursor in its content, it can not select it.

**Comment by redguardtoo** [comment]
The program can only select item from open/close tags for now. Select item from the middle is interesting idea, I will consider it.

**Comment by linchen2chris** [comment]
That would be nice, looking forward...
