### ISSUE TITLE
Matchit jumping in self-closing tags

### ISSUE THREAD

**Issue by ianpan870102** [redguardtoo/evil-matchit#121]
First of all, thanks for this package! I can now jump between matching `<div>` tags in HTML/web-mode as I always wanted. Here I'd like to report 2 issues that I encountered to help perfect this package.

## Issue 1
I've noticed that **for self-closing tags**, the behaviour is quite unpredictable.

Consider this example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
  </head>
  <body>
    <p>Hello world!</p>
  </body>
</html>
```

I can jump between the opening and closing tags of `html`, `head`, `body` etc. as expected. However, for `<link />`, which is a self-closing tag, I can only jump from the opening angle bracket to the closing one, and not the other way around.

## Issue 2
**Another minor issue** that I found, is if I put my cursor position on the "slash" of the closing tag, for example, `<|/html>`, or `<|/head>`, then evil-matchit will not be able to jump me to the correct opening `<html>` or `<head>`.

**Comment by redguardtoo** [comment]
fixed in latest version

**Comment by ianpan870102** [comment]
Thanks! I can confirm that the latest update **fixed both of my issues**. Closing thread.
