### ISSUE TITLE
f90 mode plugin rule

### ISSUE THREAD

**Issue by qiUip** [redguardtoo/evil-matchit#122]
I've tried using evil-matchit with f90-mode and couldn't get it to work.  Switching to fortran-mode resolved the issue.
I had a quick look at the source, and in evil-matchit.el lines 188-189 saw that f90 should have been f90-mode.  After making that change it works as intended.    

Current code on evil-matchit.el :
```
;; Fortran
(evilmi-load-plugin-rules '(f90 fortran-mode) '(fortran))
```

**Comment by redguardtoo** [comment]
437f676 fix f90-mode bug, add fortran unit test (Chen Bin)
