### ISSUE TITLE
Error when jumping inside Elisp comment.

### ISSUE THREAD

**Issue by Janfel** [redguardtoo/evil-matchit#124]
To reproduce this bug, open a new `emacs-lisp-mode` buffer like this:

```elisp
|;; test
```

The character `|` marks the point. When pressing `%` or calling `M-: (evilmi-sdk-scan-sexps t)` an error of the form `(wrong-type-argument number-or-marker-p nil)` occurrs. I suspect the cause are the lines [91](https://github.com/redguardtoo/evil-matchit/blob/ae8fddea392441229ed8c3038f7c0ea94dbac9dc/evil-matchit-sdk.el#L91) and [116](https://github.com/redguardtoo/evil-matchit/blob/ae8fddea392441229ed8c3038f7c0ea94dbac9dc/evil-matchit-sdk.el#L116) of `evil-matchit-sdk.el`. The variable `e` is first initialized to `nil`, as none of the `cond` clauses fit, and is then compared as a number with `=`.

**Comment by redguardtoo** [comment]
8fba4f1 minor issue in emacs lisp comment (Chen Bin)
