### ISSUE TITLE
evilmi--operate-on-item: Wrong type argument: integer-or-marker-p, nil

### ISSUE THREAD

**Issue by tshu-w** [redguardtoo/evil-matchit#127]
## Steps to reproduce
1. emacs -Q -l ~/.emacs.d/test.el
2. input `'abc'`
3. press `%` at latter `'`
```emacs-lisp
;;; emacs -Q -l ~/.emacs.d/test.el

(setq package-archives '(("melpa" . "https://melpa.org/packages/")
                         ("org"   . "https://orgmode.org/elpa/")
                         ("gnu"   . "https://elpa.gnu.org/packages/")))

;; initialize packages
(unless (bound-and-true-p package--initialized) ; To avoid warnings in 27
  (setq package-enable-at-startup nil)          ; To prevent initializing twice
  (package-initialize))

;; setup `use-package'
(unless (package-installed-p 'use-package)
  (when (not package-archive-contents)
    (package-refresh-contents))
  (package-install 'use-package))

(require 'use-package)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(setq initial-major-mode 'text-mode ;; "start with the *scratch* buffer in text mode"
      initial-scratch-message nil)  ;; "make scratch buffer empty"

(use-package evil
  :ensure t
  :init
  (evil-mode))

(use-package evil-matchit
  :ensure t
  :init (global-evil-matchit-mode))
```

## Backtrace
```
Debugger entered--Lisp error: (wrong-type-argument integer-or-marker-p nil)
  evilmi-sdk-simple-jump()
  evilmi--operate-on-item(nil)
  evilmi-jump-items(nil)
  funcall-interactively(evilmi-jump-items nil)
  call-interactively(evilmi-jump-items nil nil)
  command-execute(evilmi-jump-items)
```

**Comment by redguardtoo** [comment]
5391923 fixed minor bug #127 (Chen Bin)

**Comment by tshu-w** [comment]
@redguardtoo There are no errors thrown now, but press % on the latter single quotes won't jump back to the front, and the double quotes are equally somewhat of a problem.

**Comment by redguardtoo** [comment]
That's right behavior because `'abc'` is not string. Try `"abc"` instead. 
![evil-matchit-jump](https://user-images.githubusercontent.com/184553/92318204-2c526700-f04c-11ea-962a-c9631d100469.gif)

**Comment by tshu-w** [comment]
I try on text-mode, should it consider `'abc'` as a string? In addition, `"abc"` is also strange in text-mode(I press '%' on latter quotes and the cursor jump to a)
![Kapture 2020-09-06 at 15 02 04](https://user-images.githubusercontent.com/13161779/92320219-763e4b80-f052-11ea-85f7-0f060c1ba929.gif)

**Comment by redguardtoo** [comment]
`(get-text-property (point) 'face)` should be `font-lock-string-face`

**Comment by tshu-w** [comment]
I do not quite understand, but I got `nil` both at double quotations and single quotations in text-mode. What can I do to make the quotes jump to each other in text-mode and org-mode?

**Comment by redguardtoo** [comment]
text-mode is a bit tricky. There is no existing API I can use. Let me think about a solution.

**Comment by tshu-w** [comment]
what about org-mode? In fact, I mainly use org-mode

**Comment by redguardtoo** [comment]
`org-mode` derives from `text-mode`. Let me do some investigation.

**Comment by tshu-w** [comment]
BTW, the original `evil-jump-item` can jump between `()` in org-mode, `evilmi-jump-items` cannot.

**Comment by redguardtoo** [comment]
should work on this issue,
- jump between quote character in text-mode, org-mode
- jump between brackets in org-mode

**Comment by redguardtoo** [comment]
* 9cd0dda 2021-06-09 can jump between quotes in plain text (Chen Bin)
* 3076a8c 2021-06-09 org-mode can use simple rule (Chen Bin)

**Comment by tshu-w** [comment]
@redguardtoo Thank you, I will have a try.

**Comment by redguardtoo** [comment]
Feel free to re-open this ticket or create a new ticket if it's not fixed
