### ISSUE TITLE
Compatibility with $ in visual mode

### ISSUE THREAD

**Issue by toyboot4e** [redguardtoo/evil-matchit#129]
Example:

![match](https://user-images.githubusercontent.com/47905926/100499569-f4237600-31ad-11eb-96c7-c4dc7b446447.gif)

1. Press `V`
2. Press `$`
3. Press `%`
4. The cursor goes to an unintented point (I thought it would go to `(use-package evil-matchit`)

Thank you.

**Comment by redguardtoo** [comment]
2b9b687 fixed: cannot jump back from the line end in visual mode (Chen Bin)

**Comment by toyboot4e** [comment]
I tried and looks good! Thank you so much <3
