### ISSUE TITLE
Feature request: make evil an optional dependency

### ISSUE THREAD

**Issue by QiangF** [redguardtoo/evil-matchit#137]
Maybe make it to work better with vanilla emacs, because evil-mode is quite heavy.

**Comment by gf3** [comment]
This is something I'm interested in as well! I'd love to be able to use it with [meow](https://github.com/meow-edit/meow)

**Comment by redguardtoo** [comment]
d72471b make evil related code a single module (Chen Bin)

For preview only. Use `evilmi-jump-items-native` instead of `evilmi-jump-items` and ignore minor mode when evil is not installed. 

Other commands always works with or without evil.

**Comment by gf3** [comment]
@redguardtoo wow! you're amazing—thank you! i will give this a try
