### ISSUE TITLE
Font face / background color of MatchIt

### ISSUE THREAD

**Issue by ReneFroger** [redguardtoo/evil-matchit#36]
Hi Chen!

Thanks for the useful plugin. However, I was wondering if it's possible to customize the background color of matchit? When I do `M-x customize-group` I see there are no options available for Matchit. 

Any suggestions? I tried to detect the font face of MatchIt, but I couldn't find it. 

Spec: I have Windows 7 x64, I installed Emacs 25 from [here](emacsbinw64.sourceforge.net). 

Thanks in advance for your reply!

**Comment by redguardtoo** [comment]
what's your use case? could you give me more details?

**Comment by ReneFroger** [comment]
No use case,I'm hardcore tinkerer. :smiley: I just like to change the grey background color to dark red color.

**Comment by redguardtoo** [comment]
Google emacswilki Color theme

**Comment by ReneFroger** [comment]
You mean [this](http://www.emacswiki.org/emacs?action=browse;oldid=ColorTheme;id=ColorAndCustomThemes)?

If so, I will try to figure it out then!  Thanks for replying.

**Comment by redguardtoo** [comment]
Yes exactly


发自我的 iPhone

**Comment by ReneFroger** [comment]
I know that page very well. I have even my own colorscheme. 

But I couldn't find any relevant section on that page, which explains how to detect the color properties of your plugin.

**Comment by redguardtoo** [comment]
there is no color properties of my plugins, I didn't specify any font-face.
