### ISSUE TITLE
Jumps not working on visual mode

### ISSUE THREAD

**Issue by Orgil** [redguardtoo/evil-matchit#42]
while selection is active i can't jump into pair, gives no matching item found on current line.

**Comment by redguardtoo** [comment]
what's your major-mode?

**Comment by Orgil** [comment]
i've tried with webmode cc-mode. evilmi-version = 1.5.1

**Comment by redguardtoo** [comment]
it works on my computer, could you show me the exact step?

**Comment by Orgil** [comment]
Basically, press "v" and go into visual mode then % to jump to pair. it should select content between pair. On normal mode it works fine.

**Comment by redguardtoo** [comment]
I remove my emacs setup, and install evil/webb-mode/evil-matchit from melpa, but cannot reproduce the bug, emacs24.4.1 on Gentoo Linux,

![screencast](https://cloud.githubusercontent.com/assets/184553/7553147/8ba2d8b2-f727-11e4-8878-93508b3a969e.gif)

**Comment by Orgil** [comment]
Thanks for taking your time. I'm relatively new to the emac, moving from vim. if it is possible, could you please check out my emac setting. it is in https://github.com/Orgil/dot-emacs. There might have plugin or setting issue.

**Comment by redguardtoo** [comment]
No problem, I will check you setup at home.

**Comment by Orgil** [comment]
Thanks

**Comment by redguardtoo** [comment]
still cannot reproduce the issue, emacs24.4 with your setup on Gentoo Linux, tested the hello.html (check my hello project on github), what's your key binding for `%`?  Should be `M-x evilmi-jump-items`.

My plugin is pretty stable for a very long time. Did you have key binding interceptor on your desktop?

Have you upgraded the evil to the latest version?

**Comment by Orgil** [comment]
Thats strange. i'm using mac on both work and home with yosemite 10.10.3, emacs 24.4.1. It is not working on both machine. Evil is upgraded to latest and i don't have any key intercepter, no key binding at all for %. Even i tried directly with command M-x evilmi-jump-items still giving me "No matching item found on the current line" message. Also I removed all plugins and reinstall only evil, evil-matchit and webmode. No luck.

Also, i'm not sure if it is bug or intended but have you tried on self closing html elements like <br />? put cursor on < and press %. it jumps to end but can't go back.

**Comment by redguardtoo** [comment]
create a sample html and send it to me.

**Comment by QiangF** [comment]
It happens to me too.  emacs 24.4 with evilmi-version = 1.5.2 on debian jessie. 
I was trying to select a pair of parenthesis, like (hello world), the jump works fine in normal state, but it give this error in visual state:
user-error: No matching item found on the current line
This happens to other pairs too.
I looked the key binding for % up with c-h k in evil visual state, the help says:
% runs the command evilmi-jump-items, which is an interactive autoloaded
  compiled Lisp function in `evil-matchit.el'.
It is bound to %, <visual-state> %, <normal-state> %.

**Comment by redguardtoo** [comment]
Yes, I can confirm that. Looks it's evil-mode has some issue, it's character under cursor is different in visual and normal mode.

**Comment by QiangF** [comment]
Maybe you can write a function for visual mode seperately,  switch to normal mode and jump to the match and record the point then switch to visual mode again and select the region.
Thank you for this package, it works perfectly otherwise!

**Comment by redguardtoo** [comment]
thanks. I already figured out a simpler solution.
69a7130 can jumpt between brackets in visual-state #42 (Chen Bin)

Should work now, if it's not resolved, feel free to re-open the issue.

**Comment by Orgil** [comment]
Thanks for update. I can now jump with character selection mode. But can't jump with row selection.
v % works. but "shift+v %" not jumping in all modes with evil-mode.
