### ISSUE TITLE
easy way to add new tags to existing language?

### ISSUE THREAD

**Issue by VanLaser** [redguardtoo/evil-matchit#46]
If I want to add several matching tags to, let's say, the C and C++ languages, what is the easiest way to do it (i.e. add "something* to my `init.el`), without overwriting the `evilmi-c-match-tags` and without modifying the plugin? For example, I'd want something like "if" <-> "else", and "do" <-> "while" to match on `%`.

**Comment by redguardtoo** [comment]
step 1: `(add-to-list 'evilmi-c-match-tags '("begin-keyword" "middle-keyword" "end-keyword")`
step 2: `(add-to-list 'evilmi-c-extract-keywords-howtos '(regex 1))`

**Comment by VanLaser** [comment]
I did figure the 1st step (not the 2nd, though) but my problem seems to be finding a good moment to add those tags to the list. I tried something like this:

      (add-hook 'c-mode-hook '(lambda ()
                                  (progn
                                    (add-to-list 'evilmi-c-match-tags '("if" "" "else"))
                                    (add-to-list 'evilmi-c-extract-keyword-howtos '(regex 1)))))
        (add-hook 'c++-mode-hook '(lambda ()
                                  (progn
                                    (add-to-list 'evilmi-c-match-tags '("if" "" "else"))
                                    (add-to-list 'evilmi-c-extract-keyword-howtos '(regex 1)))))

... but, when checking with `C-h v` `evilmi-c-match-tags`, the list doesn't seem to be updated.
(I'm pretty new to Emacs, it's pretty sure that I'm doing some obvious mistakes).

**Comment by VanLaser** [comment]
Finally solved it:

      (with-eval-after-load 'evil-matchit-c
        (add-to-list 'evilmi-c-match-tags '("if" nil "else" "MONOGAMY")))

I hope you manage to implement [this issue](https://github.com/redguardtoo/evil-matchit/issues/25) - when `if`/`else` and their `{` are not on the same line, the `{` "captures" the match and you can't go back (from `else` to `if`).

Thank you for the plugin! Closing this question.

**Comment by redguardtoo** [comment]
Check `evilmi-init-plugins`, you only need define two functions `your-get-tag-from-current-line` and `jump-to-the-match` and insert it into the global variable `evilmi-plugins`. There is no limitation on how you define the function.

**Comment by redguardtoo** [comment]
af40d30 documentation (Chen Bin)

I updated README.

**Comment by VanLaser** [comment]
Thanks! Emacs + Evil plugins rocks :)
