### ISSUE TITLE
What's new in v2.0?

### ISSUE THREAD

**Issue by PythonNut** [redguardtoo/evil-matchit#47]
I just dropped by and noticed that there was a major version change (to `v2.0`)? However, I can't tell what's actually changed. Perhaps you can add a little blurb in the README (or maybe the wiki, or maybe in the tag release notes) telling us what to celebrate about.

**Comment by redguardtoo** [comment]
The major feature is you can jump between the begin/end of string. It works out of the box when you press `%`. So from user's point of view, nothing new to learn.

You can customize the definition of string, for example, comment in C code could be regarded as string wrapped in "/". Check the advanced tips in README.

From technical point of view, I don't use evil API any more. That makes this package more robust.
Besides, bugs are fixed.

**Comment by PythonNut** [comment]
Ah, cool. Thanks!
