### ISSUE TITLE
Lua mode function jump not working

### ISSUE THREAD

**Issue by zilongshanren** [redguardtoo/evil-matchit#48]
When the cursor is on `function` keyword, when I press %, I want to jump to the `end` keyword.
But it does to the first parenthesis.

```
 getPos = function(self, x, y)
        return x+1, y+1
    end

```

**Comment by redguardtoo** [comment]
8862d8e support for statement in lua-mode (Chen Bin)

**Comment by andyque** [comment]
@redguardtoo  Still not working? Any suggestions?

**Comment by redguardtoo** [comment]
should work, check the version, 2.0.1

**Comment by andyque** [comment]
```local function initGLView()
    local director = cc.Director:getInstance()
   
end
```
If there are `local` keyword before the function keyword, the jump fails..

**Comment by redguardtoo** [comment]
11352e2 support more pattern in lua-mode (Chen Bin)
