### ISSUE TITLE
Not working in python mode

### ISSUE THREAD

**Issue by QiangF** [redguardtoo/evil-matchit#62]
Hello Sir,
I am using version 2.1.1 with emacs 24.4.
I place my cursor on the end of the last line of this code:

```
    for file in files:
        conc = [np.float(ii[0].split(',')[1]) for ii in conc.split()]
```

I expect to jump to the '[' after '=' on the same line, but it jumps to the beginning of the first line. evil-jump-item works correctly here.
Thank you!

**Comment by redguardtoo** [comment]
That's by design.  because I cannot tell whether you want to jump to the beginning of  for.

**Comment by QiangF** [comment]
Thank you. I will bind it to another key.

**Comment by redguardtoo** [comment]
I will design a flag to let user decide which algorithm take priority

**Comment by QiangF** [comment]
Hello Sir,
I am trying too make two quick % run evilmi-jump-items in python mode, but seems there is something missing in the following code, I'd appreciate a lot if you can have a look.

    (defvar my-double-key-timeout 0.25
    "The number of seconds to wait for a second key press.")

    (defun my/jump()
    (interactive)
    (let ((last-called (get this-command 'my-last-call-time)))
        (if (and (eq last-command this-command)
            (<= (time-to-seconds (time-since last-called)) my-double-key-timeout))
            (call-interactively 'evilmi-jump-items) 
            (if (sit-for my-double-key-timeout)
                (call-interactively 'evil-jump-item)))
        (put this-command 'my-last-call-time (current-time))))

**Comment by redguardtoo** [comment]
http://stackoverflow.com/questions/10569165/how-to-map-jj-to-esc-in-emacs-evil-mode , looks similar. I reopen the issue, I will add some extra flag this weekend.

**Comment by QiangF** [comment]
Weird, after a restart, it works for me now without any change. The benifit of my setting is you don't need another package. I am closing this issue. Thank you!
Also there is key-combo which seems to do more than key-chord.

**Comment by redguardtoo** [comment]
cool.

**Comment by olejorgenb** [comment]
Did you create a flag?

I understand the difficulty in creating sane behavior for all cases though. Personally I find the current behavior annoying though, but it obviously depends on the usage pattern. An argument against the current behavior is that `%` traditionally only works with brackets(?) and the principle of least surprise. (there's other ways to move up an block too)

**Comment by redguardtoo** [comment]
Thanks for the feedback. If the the character under cursor is among `([{`, I will jump to the matching `)]}` instead. Flags is not necessary.

**Comment by olejorgenb** [comment]
I'm not sure I understand.  (I'm using version 2.1.9 inside spacemacs)

The problem is when the last character in a block is among `}])"`. When the cursor is on that char `%` (`evilmi-jump-items`) jumps to the start of the block instead of the matching `{[("`

Test case:

    if something:
      some_action(some_arg)
                          ^

Pressing `%` jumps to `if` not, `(`.

I understand why that is one of two possible behaviors, but I prefer the second one. (I see now that this is a port of a vim plugin. That presumably have the first behavior so I guess it actually is "the least surprise" :))

**Comment by redguardtoo** [comment]
Yeah, I think it's a bug and I will fix it.

**Comment by redguardtoo** [comment]
After studying the code history, I thought my original design is better.

But you can `(setq evilmi-always-simple-jump t)` in v2.2.1 if you prefer different way to match tags.
