### ISSUE TITLE
Matching when on a bracket and inside it like matchit.vim

### ISSUE THREAD

**Issue by srustamo** [redguardtoo/evil-matchit#66]
Perhaps I'm missing an existing feature, but with `evil-matchit` placing a point on the first `<` in this statement `<head> Hello </head>` and pressing <kbd>%</kbd> will jump to `</head>` element. `matchit.vim` will jump to `>` element of the opening `<head>` element.  

edit: `matchit.vim` will jump to a closing `</head>` element if the cursor (in vimspeak) is anywhere between `< >` but not on them.

**Comment by redguardtoo** [comment]
you can use `f >` or `F <` instead, but I think the current behavior make sense, because most time you are jumping between tags.

If in your use case, you need jump between '<>' , you can write your own rule and make it loaded before evil-html,
```lisp

  (mapc (lambda (mode)
          (plist-put evilmi-plugins mode '((evilmi-template-get-tag evilmi-template-jump)
                                           (evilmi-simple-get-tag evilmi-simple-jump)
                                            (evilmi-your-get-tag evilmi-your-jump)
                                           (evilmi-html-get-tag evilmi-html-jump)))
          )
        '(web-mode html-mode nxml-mode nxhtml-mode sgml-mode message-mode))
```

**Comment by srustamo** [comment]
Could you please give me a full working config for jumping between two `div`s (rather than between matching `<>`) in the html below:
```html
<div>
	<link rel="stylesheet" /css/font-awesome.min.css">
</div>
```

**Comment by redguardtoo** [comment]
```lisp
(require 'evil-matchit)
(global-evil-matchit-mode 1)
```
Official setup works.

You major mode should be of `web-mode html-mode nxml-mode nxhtml-mode sgml-mode message-mode`

**Comment by srustamo** [comment]
I'm in `sgml-mode` editing the code above. Hitting <kbd>%</kbd> inside the the first `<div>` - point on `d` letter - takes me to the very first `<`. My desired behaviour is that it should take me to the closing `</div>`.

**Comment by redguardtoo** [comment]
`evilmi-version`?

**Comment by srustamo** [comment]
2.1.4

**Comment by redguardtoo** [comment]
`C-h k %` in evil-normal-state?

**Comment by srustamo** [comment]
% runs the command evil-jump-item (found in evil-motion-state-map), which is an
  interactive compiled Lisp function in ‘evil-commands.el’.

It is bound to %.

(evil-jump-item &optional COUNT)

Find the next item in this line after or under the cursor
and jump to the corresponding one.

[back]

**Comment by redguardtoo** [comment]
you should bind `%` to evilmi-jump-items. place my setup after `(evil-mode 1)`

**Comment by srustamo** [comment]
Sorry, I have confused you, because I forget that I disabled the `evil-matchit` mode, because of the intended by your behaviour. My original question (please see the very first post) is to match the behaviour of `matchit.vim` (described in the first post). 

And my follow up post was to ask for your help to produce this behaviour through configing your package, which you seem to imply is possible.

**Comment by redguardtoo** [comment]
There are many things I don't like about vim-matchit. For example, jumping between `<>`.

But`evil-matchit`  gives you full freedom to DIY, like Emacs. So now is the good time to learn lisp.

Here is a prototype you can copy to your ~/.emacs after evil-matchit setup,
```lisp
(defun evilmi-your-get-tag ()
  (if (or (= (following-char) 60) ;<
          (= (following-char) 62)) ;>
      (list (point))))
(defun evilmi-your-jump (rlt num)
  (if (= (following-char) 60) (search-forward ">" nil nil))
  (if (= (following-char) 62) (search-backward "<" nil nil))
  (point))
(plist-put evilmi-plugins 'sgml-mode '((evilmi-template-get-tag evilmi-template-jump)
                                       (evilmi-simple-get-tag evilmi-simple-jump)
                                       (evilmi-your-get-tag evilmi-your-jump)
                                       (evilmi-html-get-tag evilmi-html-jump)))
```

**Comment by srustamo** [comment]
Many thanks for trying to help. I tried the code starting the `evilmi-your-get-tag` function. I don't see any change in the original behaviour. `C-h-v` `evilmi-plugins` yields this for `sgml-mode`: 

```elisp
 sgml-mode
 ((evilmi-template-get-tag evilmi-template-jump)
  (evilmi-simple-get-tag evilmi-simple-jump)
  (evilmi-html-get-tag evilmi-html-jump))
```
Looks like `(plist-put)` does not do its job.

**Comment by redguardtoo** [comment]
thanks. Looks this is a bug in evil-matchit which always reset evilmi-plugins when minor-mode enabled.  Fixed.

b01763b initialize evilmi-plugins only once v2.1.5 (Chen Bin)

**Comment by srustamo** [comment]
Thanks. I hope it will be pushed to Melpa soon.

**Comment by redguardtoo** [comment]
already there http://stable.melpa.org/#/evil-matchit

**Comment by srustamo** [comment]
Thanks. I see that `evilmi-plugins` gets updated properly now. However, the plugin code for jumping between `<>` still does not work.

I understand if you don't want to spend more time on this issue. If you still have a spare moment, please have a look if it works for you.

**Comment by redguardtoo** [comment]
It's working in v2.1.5, make sure you are using sgml-mode, `C-h v major-mode`,

Here is my evil-matchit -setup,
```lisp
(require 'evil-matchit)
(global-evil-matchit-mode 1)
(defun evilmi-your-get-tag ()
  (if (or (= (following-char) 60) ;<
          (= (following-char) 62)) ;>
      (list (point))))
(defun evilmi-your-jump (rlt num)
  (if (= (following-char) 60) (search-forward ">" nil nil))
  (if (= (following-char) 62) (search-backward "<" nil nil))
  (point))
(plist-put evilmi-plugins 'sgml-mode '((evilmi-template-get-tag evilmi-template-jump)
                                       (evilmi-simple-get-tag evilmi-simple-jump)
                                       (evilmi-your-get-tag evilmi-your-jump)
                                       (evilmi-html-get-tag evilmi-html-jump)))
```

**Comment by srustamo** [comment]
All is well. Thank you.
