### ISSUE TITLE
Intraline matches

### ISSUE THREAD

**Issue by jmcarthur** [redguardtoo/evil-matchit#69]
Does evil-matchit not support jumping between keywords on the same line? Other than parens, etc., I can't find any examples of this. The sdk doesn't seem designed to support this at all, and I can't find any modes which appear to support jumping within a single line or even having a single line contain the end of one matched pair and the beginning of another. Perhaps I simply misunderstand how this package is meant to be used?

**Comment by redguardtoo** [comment]
Sorry evil-matchit does not support matching between keywords in same line yet.
What's your use case?

**Comment by jmcarthur** [comment]
I primarily work in expression based languages, and common coding styles do
not necessarily put all the interesting keywords on different lines from
each other.

**Comment by redguardtoo** [comment]
What do you mean expression language? Could you give me some sample?
Actually, the evil-matchit is very versatile, the key information you need provide to the main frame work,
- a function to return the meta info from current point, meta info format is defined by you
- a function to use that the meta info and jump to certain position

So you can easily support any new language in evil-matchit, check the README.

I have only limited resource. So I can only support most popular languages and language I'm using.
but I'm open for pull requests.

**Comment by jmcarthur** [comment]
For that matter I am surprised that this doesn't already bother you. For
example, do you never put the opening and closing tag for some HTML block
on the same line? Disclaimer: I haven't tried the HTML support... It might
already work. In any case, my main complaint is that it's not very easy to
add a new language supporting this. It wasn't immediately clear to me that
the sdk only supports moving from one line to another.

I at least wanted to confirm whether I was misunderstanding the current
limitations of the API, and if not then propose adding support for this
(common, I would have expected) use case to the sdk. I'm not offended of
this ticket ends up being wontfixed or just sits around for a while. I also
don't really have the time to make evil-matchit do exactly what I want, so
I understand where you're coming from.

**Comment by redguardtoo** [comment]
can you show me some sample, what specific language you are using?

Different language has different implementation. evil-matchit.el is actually a generic framework which does not force you anything.

For HTML, I use emacs own sgml API, so it can jump in one line perfectly.

For other programming language, I have different implementation.  a few language has some shared patterns, so they use sdk.el. but sdk.el is not requirement. For example, python does not use sdk. 

So there is NO limitation in my API. the only API exists in  evil-matchit.el, nothing more. evil-matchit-sdk.el is just some OPTIONAL utility.

As for your concern for move between lines,  it's just I choose certain implementation as practical solution. If you read evil-matchit.el, you will find any implementation can be replaced in real time.

**Comment by jmcarthur** [comment]
It's okay. I might just go through the trouble to implement what I need manually. I was just hoping the SDK could help here, but it seems it cannot, and it is not intended to.
