### ISSUE TITLE
Jumping back from inline math tag in latex

### ISSUE THREAD

**Issue by justbur** [redguardtoo/evil-matchit#70]
With the latex code `$f(x)=x^2[$] normal text $g(x)=2$` and point `[]` matchit jumps forward to the next `$` instead of back to the opening one. Is there any way to fix this? I noticed that `show-paren-mode` highlights the correct match.

I also know about the `\(\)` tags, but would prefer to not have to use them. Thanks

**Comment by redguardtoo** [comment]
c675e74 can simple jump in latex-mode, #70 (Chen Bin)

**Comment by justbur** [comment]
Sorry, I don't understand your comment

**Comment by redguardtoo** [comment]
I solved your problem.

**Comment by justbur** [comment]
I just tested my example with the latest version and it is still jumping forward from the point. 

Maybe I have to set something? I am just using `global-evil-matchit-mode`

**Comment by redguardtoo** [comment]
looks it's `latext-mode` implementation is buggy so `scan-sexps` fail. workaround by fallback to evil API.

4780ef4 scan-sexps buggy in latex-mode, fallback to Evil API (Chen Bin)
