### ISSUE TITLE
"action %" does not work

### ISSUE THREAD

**Issue by xuhdev** [redguardtoo/evil-matchit#73]
In Vim, one can perform an action for the range of the text between the current cursor position and the after-motion position. However, evil-matchit does not seem allow it. For example,

    <h1>sdfa<em>efewa</em></h1>

Move the cursor to `<h1>` and push `%` -- the cursor moves to `</h1>` as expected. However, `d%` gives the following error: "No matching item found on the current line" -- it is supposed to delete whatever between this pair.

**Comment by redguardtoo** [comment]
use `dit`, evil-matchit assume the beginning and end tag are at different lines when working on text objects.

**Comment by xuhdev** [comment]
Sorry for the poor example -- I really meant it as a demo. You can have a Ruby code block that cannot be deleted by using `%`, for example:

```ruby
def say_hello
   return 'hello'
end
```

Put the cursor on `def`. `d%` won't delete the code block.

**Comment by redguardtoo** [comment]
`da%` or `di%`

**Comment by xuhdev** [comment]
OK, that makes sense. Thanks!
