### ISSUE TITLE
Doesn't jump on close parenthesis of `print('hello')`

### ISSUE THREAD

**Issue by off99555** [redguardtoo/evil-matchit#75]
#### Description :octocat:
`%` key (jump to matching paren) does not work correctly in Python mode
#### Reproduction guide :beetle:
- Start Emacs and activate *evil-matchit*
- Type `print('hello')`
- Move point to the last parenthesis
- Press `%` you will notice that the point does not jump to the matching
  parenthesis

*Observed behaviour:* :eyes: :broken_heart:
The point does not jump. 

*Expected behaviour:* :heart: :smile:
The point should jump to the matching parenthesis.

#### System Info :computer:
- OS: windows-nt (Windows 10) Occurs in other OS too
- Emacs: 25.1.1
- Graphic display: t
- Distribution: spacemacs

**Comment by robbyoconnor** [comment]
@off99555 -- I wasn't clear: 

It works fine -- HOWEVER there is a bug -- and we probably need to tweak it..It **DOES** work as you're saying...this may be an emacs 25 issue but I doubt it.

**Comment by robbyoconnor** [comment]
What doesn't work is if you have something like (horribly contrived): 

```
def foo(bar):
  baz = True
  foo = True
  if baz or (foo):
    return 3
  elif bar:
    print "Hi"
  else:
    return 5
  return 3
```

Place the cursor on the `if` -- it will jump to the parens and not jump between the clauses.

**Comment by redguardtoo** [comment]
@off99555 , it's a known issue, the work around is add some comment after `print('hello')`.

**Comment by robbyoconnor** [comment]
@redguardtoo, I'm using Emacs 26 -- so there's probably that BUT I don't use python often..

**Comment by off99555** [comment]
OK. So it's not a bug but intended feature.
But you should make it jump to the matching paren instead because if you want to jump to the statement you can easily do `0%`.

**Comment by off99555** [comment]
Closing this issue now, the problem is resolved after adding `(setq evilmi-always-simple-jump t)`.
If I want to jump to the statement I can just do `0%`.

**Comment by off99555** [comment]
u

**Comment by off99555** [comment]
I think you should implement that default behavior first before the issue is closed.

**Comment by redguardtoo** [comment]
`(setq evilmi-always-simple-jump t)` is an option for and advanced user. Jump algorithm using python indentation is still usable but with lower priority when this flag is on.

Consider following snippet:
if true:
    print ('hello world')

if you place the cursor of the `)`, you either jump to the `if` or `(`. There ambiguity from design of python.

**Comment by off99555** [comment]
I don't think you should jump to the `if` in that situation. The matching paren should be number one priority.
