### ISSUE TITLE
sdk doesn't work for matching tags in the same line

### ISSUE THREAD

**Issue by neojski** [redguardtoo/evil-matchit#77]
Hi @redguardtoo,

I was trying to modify ruby's matchit for ocaml and I started with match-with, which may look like:
```ocaml
let x v = match v with
  | X -> 1
  | Y -> 2
```
but can't get the sdk to work.

I tried setting:
```elisp
(defvar evilmi-ruby-extract-keyword-howtos
  '(
    ("\\(match\\)" 1)
    ("\\(with\\)" 1)
    ))
```
and
```elisp
(defvar evilmi-ruby-match-tags
  '((
    ("match" () "with")
    ))
```

Please note that it works for:
```ocaml
let x v =
  match v
  with
  | X -> 1
  | Y -> 2
```
but that's not how ocaml is written. Please advise how to fix it.

**Comment by redguardtoo** [comment]
tag should be on different lines (that's the assumption of evil-matchit-sdk)

if you don't use sdk (at least under certain use cases), you can ignore the limit of sdk. For example, my python implementation is different from other languages.

The dirty solution is to check the thing under cursor in `evilmi-ocaml-get-tag`. If the thing is "match", pass the thing and some flags you defined to `evilmi-ocaml-jump` which choose not to use sdk for this specific thing.

**Comment by neojski** [comment]
Would be helpful to document that assumption.

Is it really important for the matching tag to be on the same line? It sounds to me like a pretty artificial constraint.

**Comment by redguardtoo** [comment]
If you don't use match sdk, then there is no limitation. I will update README.

**Comment by neojski** [comment]
I implemented support for ocaml which is fairly generic and doesn't have these limitations: https://github.com/redguardtoo/evil-matchit/pull/78.
