### ISSUE TITLE
% should search for the first keyword in the current line

### ISSUE THREAD

**Issue by neojski** [redguardtoo/evil-matchit#80]
Pressing <kbd>%</kbd> with cursor on `m` should jump to end:
```ocaml
|module Stable = struct
...
end
```
Please note that evil-matchit also behaves incorrectly with parenthesis:
```
|foo ( bar )
```
If you have cursor on `f` and press <kbd>%</kbd> you should end up on `)`.

For ocaml it would mean modifying https://github.com/redguardtoo/evil-matchit/blob/bed39041b1181ec26cf2601a8a7aa4afe2510f5b/evil-matchit-ocaml.el#L69 to find the first keyword in the current line.

There's also some work in https://github.com/redguardtoo/evil-matchit/blob/bed39041b1181ec26cf2601a8a7aa4afe2510f5b/evil-matchit-simple.el but I'm not entirely familiar with that one.

**Comment by redguardtoo** [comment]
In first case, you can `(goto-char (cdr (bounds-of-thing-at-point 'word)))` at the end of `evilmi-ocaml-jump`.

In second case, I'm not familiar with Ocaml syntax so I don't know what's the right way to jump. As I remember `scan-sexps` is used to jump between brackets.
