### ISSUE TITLE
[Feature Request] Support for elixir?

### ISSUE THREAD

**Issue by dsdshcym** [redguardtoo/evil-matchit#83]
Thanks for this great package! I've been using it for a long time.

But I found this package haven't supported elixir yet. Do you have any plan for this?

I think elixir support it's pretty simple (in my smartparens config, i only set `do/end`, `fn/end` pairs for elixir). But I'm not familiar with `evil-matchit` and with a simple glance, I think it's not trivial to add support for a new language. So I'm opening this issue here.

**Comment by redguardtoo** [comment]
I'm open mind to new languages.

Pull request is welcome. It's pretty simple add any new languages. Maybe this weekend I will write a tutorial for beginners on how to support new language.

**Comment by dsdshcym** [comment]
Cool! Thanks!

I checked the SDK (https://github.com/redguardtoo/evil-matchit#use-sdk) and I might try to implement a simple one for elixir if I have time this weekend.

**Comment by redguardtoo** [comment]
50bb882 support elixir (Chen Bin)

**Comment by dsdshcym** [comment]
Thanks for the support!

But there are still two minor issues:
1. In elixir, there are many one-liner function definitions like:
```elixir
def add(a, b), do: a + b
```
In this case, the `def`-`end` pair will mismatch.

My solution is to only match `do`-`end` pairs, since all `def` syntax are using `do`-`end`.

2. It doesn't support one-liner anonymous functions like: 

``` elixir
fn (a, b) -> a + b end
```

I don't know how to match multiple keywords in a single line, maybe it's a constraint from the sdk?

**Comment by redguardtoo** [comment]
I think your previous pull request has already solve issue 1.

"20270ab support one liner (Chen Bin)" fixed issue 2

**Comment by dsdshcym** [comment]
Thanks a lot for your patience and help!
I think the support for Elixir is great now and I'll consider this issue resolved.
