### ISSUE TITLE
Ruby - jumping between words in the middle of the line fails

### ISSUE THREAD

**Issue by kriansa** [redguardtoo/evil-matchit#85]
When I use % to jump between pairs of Ruby words, if they are not in the beginning of the line, it won't find the proper match.

Failing examples:

```ruby
# Inline method
def my_method; end

# Condition value assignment
a = if true
      1
    else
      2
    end

# Inline condition value assignment
b = if true then 1 else 2 end
```

I understand that this might be difficult to implement, since in Ruby you can have inline condition statements like this:

```ruby
value = something if 1 == 1

# There's no else or then!
```

**Comment by redguardtoo** [comment]
maybe you could provide some patch? Currently I'm working on `counsel-etags`. This project issues can only be handled on weekends.

**Comment by redguardtoo** [comment]
304f221 handle ruby statement after assign operator (Chen Bin)

But not inline statement.
