### ISSUE TITLE
OCaml documentation comments are not considered comments

### ISSUE THREAD

**Issue by m-plamann** [redguardtoo/evil-matchit#92]
If I have an OCaml file

    a
    (** test *)
    b

If point is on the "(" and I press "%", it jumps to "b".
If point is on the ")" and I press "%", it jumps to "a".

I believe this is because `evilmi-in-comment-p` looks at the font face to determine if it is in a comment:

    (defun evilmi-in-comment-p (pos)
      "Check character at POS is comment by comparing font face."
      (evilmi-current-font-among-fonts-p pos '(font-lock-comment-face
                                               font-lock-comment-delimiter-face)))

 But `tuareg-mode` assigns doc-comments `font-lock-doc-face`.

Is it possible to make evil-matchit consider `font-lock-doc-face` to also be a comment face in ocaml files?

**Comment by m-plamann** [comment]
I'm currently working around this with the following advice:
```
(advice-add
   'evilmi-in-comment-p
   :around
   (defun evil-matchit-work-around-doc-comment-bug (f pos &rest rest)
     (or (and (eq major-mode 'tuareg-mode)
              (eq (get-text-property pos 'face) 'font-lock-doc-face))
         (apply f pos rest))))
```

**Comment by redguardtoo** [comment]
1c428e1 ocaml use font-lock-doc-face for comment (Chen Bin)
