### ISSUE TITLE
mhtml-mode (emacs26): evilmi--scan-sexps: Scan error: "Containing expression ends prematurely", 1158, 1159

### ISSUE THREAD

**Issue by jackkamm** [redguardtoo/evil-matchit#94]
mhtml-mode is the new default mode for viewing html files in emacs26. evil-matchit does not seem to work with it -- most times, pressing `%` does nothing. If the cursor is at the end of a tag (i.e. on the `>` symbol within `<sometag>`), pressing `%` gives the error message:
```
evilmi--scan-sexps: Scan error: "Containing expression ends prematurely", 1158, 1159
```

**Comment by redguardtoo** [comment]
Insert below code AFTER your `evil-nerd-commenter` setup:
```lisp
(plist-put evilmi-plugins 'mhtml-mode '((evilmi-template-get-tag evilmi-template-jump)
                                        (evilmi-simple-get-tag evilmi-simple-jump)
                                        (evilmi-html-get-tag evilmi-html-jump)))
```

**Comment by jackkamm** [comment]
Thanks, it works.
